runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /.*
  script: _go_app
env_variables:
  SLACK_KEY: CiQAgjBGQm1aFTfNsTYceo46b1omBy+BvZjPPOIitEyK6opxWckSSQCdk3ogbDHvTEHHMD8V+QmKRq65dhQPaU5Fh+OsUSunVgI2HKZMFIviuxqKQs3YgrwuVALIQ3476V4VB42gaNViw7mG2/QFkns=
  SLACK_CLIENT_SECRET: CiQAgjBGQt3nuR5YR96644L9AzUKR3TKpoVhTwmULGeAGCi850ISQACdk3og8Bc5uTs9YzYiDRUGqdbphyn3MjgEYQytT6HANZtJEs7bthIzjOtAIlMH4XyFfhMERH6Jasbrl55Hyrg=
  PROJECT_ID: dice-magic
  KMSKEYRING: DiceMagic
  KMSKEY: SlackBotKeyKEK
  SLACK_BOT_USER_ACCES_TOKEN: CiQAgjBGQkAwZZ4Q68biZVm/fmBSLy4sQm5UUW+KfDX2kx7JZCcSUwCdk3ogWwNXj2mgUPbuxitIgT7Jcchr+yjDcZ/Q1uq4NKJR/gKfDTdOzZ5H5aMPnGemp0c/I4c8DI0hdwU3IFPky7Bv8eyj1bBpsC0RqAnebfk2
  