runtime: go
api_version: go1
service: default
skip_files:
  - sa.json
handlers:
- url: /.*
  script: _go_app
  secure: always
  redirect_http_response_code: 301
env_variables:
  SLACK_CLIENT_ID: "42142079431.351057397637"
  SLACK_KEY: CiQAgjBGQm1aFTfNsTYceo46b1omBy+BvZjPPOIitEyK6opxWckSSQCdk3ogbDHvTEHHMD8V+QmKRq65dhQPaU5Fh+OsUSunVgI2HKZMFIviuxqKQs3YgrwuVALIQ3476V4VB42gaNViw7mG2/QFkns=
  SLACK_CLIENT_SECRET: CiQAgjBGQhjtkEpkxeOLiJe5IRYKHEDNAYX0ASYc3EXKC3X1GBISSQCdk3oga7SendFnR4UGGbtGRJN4KuZVvdMzy4+4scNRC7K9p7HO2tvlsP4IOfVjFITeYn9PHWLZAF2ODGHlFlOlCRImikR9NRA=
  SLACK_CLIENT_VERIFICATION_TOKEN: CiQAgjBGQlBmE69vlQtJGtjBbyPBnp0Qxcb/1VlQ3AolZpk9LAISQACdk3ogRKdqp9JBErmWfmlOXC7rBx0Ui882rKA73eaGttOoWBqysrCFqUVJdo5e6kcLh5c14I72uRivOfu2wtA=
  PROJECT_ID: dice-magic
  KMSKEYRING: DiceMagic
  KMSKEY: SlackBotKeyKEK
  SLACK_BOT_USER_ACCES_TOKEN: CiQAgjBGQkAwZZ4Q68biZVm/fmBSLy4sQm5UUW+KfDX2kx7JZCcSUwCdk3ogWwNXj2mgUPbuxitIgT7Jcchr+yjDcZ/Q1uq4NKJR/gKfDTdOzZ5H5aMPnGemp0c/I4c8DI0hdwU3IFPky7Bv8eyj1bBpsC0RqAnebfk2