steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/chat-clients:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/dice-server:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/www:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/letsencrypt:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/chat-clients:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/chat-clients:latest',
            './app/chat-clients'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/dice-server:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/dice-server:latest',
            './app/dice-server'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/www:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/www:latest',
            './www'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/letsencrypt:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/letsencrypt:latest',
            './letsencrypt'
        ]
images: 
- 'gcr.io/$PROJECT_ID/chat-clients:latest'
- 'gcr.io/$PROJECT_ID/dice-server:latest'
- 'gcr.io/$PROJECT_ID/www:latest'
- 'gcr.io/$PROJECT_ID/letsencrypt:latest'