steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'pull-dice-server'
  args: ['pull', 'gcr.io/$PROJECT_ID/dice-server:latest']

- name: golang
  env: ['GO111MODULE=on']
  dir: './dice-server'
  args: ['go', 'build', '.']

- name: 'gcr.io/cloud-builders/docker'
  dir: './dice-server'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/dice-server-dev:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/dice-server:latest',
            '-f', 'slim.dockerfile',
            '.'
        ]


tags: ['local','dev']
images: 
- 'gcr.io/$PROJECT_ID/dice-server-dev:latest'