steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'pull-redis'
  args: ['pull', 'redis:alpine']

- name: 'gcr.io/cloud-builders/docker'
  dir: 'redis'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/redis-dev:latest',
            '--cache-from', 'redis:alpine',
            '-f', 'dockerfile',
            '.'
        ]
tags: ['local']
images: 
- 'gcr.io/$PROJECT_ID/redis-dev:latest'