steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/letsencrypt:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/letsencrypt:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/letsencrypt:latest',
            '.'
        ]
tags: ['$COMMIT_SHA']
images: 
- 'gcr.io/$PROJECT_ID/letsencrypt:latest'
- 'gcr.io/$PROJECT_ID/letsencrypt:$COMMIT_SHA'