steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/letsencrypt:latest']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'app/letsencrypt'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/letsencrypt:latest',
            # '-t', 'gcr.io/$PROJECT_ID/letsencrypt:$COMMIT_SHA',
            '--cache-from', 'gcr.io/$PROJECT_ID/letsencrypt:latest',
            '-f','dockerfile',
            '.'
        ]
# tags: ['$COMMIT_SHA']
images:
- 'gcr.io/$PROJECT_ID/letsencrypt:latest'
# - 'gcr.io/$PROJECT_ID/letsencrypt:$COMMIT_SHA'