apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt-job
  labels:
    app: letsencrypt
spec:
  template:
    metadata:
      name: letsencrypt
      labels:
        app: letsencrypt
    spec:
      containers:
      # Bash script that starts an http server and launches certbot
      # Fork of github.com/sjenning/kube-nginx-letsencrypt
      - image: gcr.io/k8s-dice-magic/letsencrypt:latest
        name: letsencrypt
        imagePullPolicy: Always
        ports:
        - name: letsencrypt
          containerPort: 80
        env:
        - name: DOMAINS
          value: "www.k8s.dicemagic.io;api.k8s.dicemagic.io" # Domain you want to use. CHANGE ME!
        - name: EMAIL
          value: certs@smallnet.org # Your email. CHANGE ME!
        - name: SECRET
          value: letsencrypt-certs
      restartPolicy: Never

---
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-certs
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: certbot
spec:
  selector:
    app: certbot
  ports:
  - protocol: "TCP"
    port: 80