apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: letsencrypt-job
  labels:
    app: letsencrypt
spec:
  schedule: "* * * * *" 
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        metadata:
          name: letsencrypt
          labels:
            app: letsencrypt
        spec:
          serviceAccountName: secret-manager
          containers:
          - image: gcr.io/k8s-dice-magic/letsencrypt:latest
            name: letsencrypt
            imagePullPolicy: Always
            ports:
            - name: letsencrypt
              containerPort: 8080
            volumeMounts:
            - mountPath: /etc/certbot-dns
              name: certbot-dns
              readOnly: true
            env:
            - name: DOMAINS
              value: "www.dicemagic.io,api.dicemagic.io" # Domain you want to use. CHANGE ME!
            - name: EMAIL
              value: certs@smallnet.org
            - name: SECRET
              value: letsencrypt-certs
            - name: DEPLOYMENT
              value: basic-ingress
            - name: NAMESPACE
              value: default  
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              capabilities:
                drop: ["ALL"]
          restartPolicy: Never
          volumes:
          - name: certbot-dns
            secret:
              defaultMode: 420
              secretName: certbot-dns 
---
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-certs
type: Opaque