apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-10-10T06:17:27Z
  generation: 1
  labels:
    app: chat-clients
  name: chat-clients
  namespace: default
  resourceVersion: "78563"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/chat-clients
  uid: 29701692-cc54-11e8-8c2c-42010a80019f
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chat-clients
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chat-clients
    spec:
      containers:
      - image: gcr.io/k8s-dice-magic/chat-clients:37fe69b1754455178f7cd87ae87f342605253fa6
        volumeMounts:
        - name: google-default
          mountPath: "/etc/google-default"
          readOnly: true
        imagePullPolicy: IfNotPresent
        name: chat-clients
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: google-default
        secret:
          secretName: google-default