apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chat-clients
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chat-clients
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chat-clients
    spec:
      containers:
      - image: gcr.io/k8s-dice-magic/chat-clients:latest
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
          requests:
            cpu: 300m
            memory: 100Mi
        imagePullPolicy: Always
        name: chat-clients
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/google-default
          name: google-default
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: google-default
        secret:
          defaultMode: 420
          secretName: google-default
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "chat-clients-service"
  namespace: "default"
  labels:
    app: "chat-clients"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 7070
  selector:
    app: "chat-clients"
  type: "NodePort"
---
apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    labels:
      app: chat-clients
    name: chat-clients-hpa
    namespace: default
  spec:
    maxReplicas: 5
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: chat-clients
    targetCPUUtilizationPercentage: 80
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
