apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-serviceaccount
  namespace: default
---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: redis
spec:
  template:
    metadata:
      labels:
        name: redis
    spec:
      serviceAccountName: redis-serviceaccount
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        - hostPort: 6379