steps:
- name: 'alpine'
  args: ['cp', 'config/dev/www/config.yaml', 'www/config.yaml']

- name: 'gcr.io/cloud-builders/docker'
  dir: 'www'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/www-dev:latest',
            '.'
        ]
tags: ['local','dev']
images: 
- 'gcr.io/$PROJECT_ID/www-dev:latest'