steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/letsencrypt:latest']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'letsencrypt'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/letsencrypt-dev:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/letsencrypt:latest',
            '-f','dockerfile',
            '.'
        ]
tags: ['local','dev']
images:
- 'gcr.io/$PROJECT_ID/letsencrypt-dev:latest'