steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'pull-chat-clients'
  args: ['pull', 'gcr.io/$PROJECT_ID/chat-clients:latest']

- name: golang
  env: ['GO111MODULE=on']
  dir: './chat-clients'
  args: ['go', 'build', '.']

- name: 'gcr.io/cloud-builders/docker'
  dir: 'chat-clients'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/chat-clients-dev:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/chat-clients:latest',
            '-f', 'slim.dockerfile',
            '.'
        ]
tags: ['local','dev']
images: 
- 'gcr.io/$PROJECT_ID/chat-clients-dev:latest'