steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/www:latest']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'www'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/www:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/www:latest',
            '.'
        ]
tags: ['local']
images: 
- 'gcr.io/$PROJECT_ID/www:latest'