baseurl = "/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Dice Magic"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "dicemagic/5"
googleAnalytics = "UA-119339106-2"

[Params]
  # homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Friendly dice rolling chatbot"
  logo = "img/DiceMagic_Big-01.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = true
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = ""
[[Params.bigimg]]
  src = "/img/bigimg1.jpg"
  desc = ""
  # position: see values of CSS background-position.
  position = "center"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Aaron Small"
  website = "https://smallnet.org"
  twitter = "Atlas_Hugged"
  linkedin = "aaron-small"
  paypal = "dicemagic"


[[menu.main]]
    identifier = "features"
    name = "Features"
    url = "/page/features"
    weight = 2
    

[[menu.main]]
    identifier = "donate"
    name = "Donate"
    url = "https://paypal.me/dicemagic/5"
    weight = 4

[[menu.main]]
    name = "Install"
    url = "page/install/"
    weight = 1
