apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: letsencrypt-job
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          name: letsencrypt
          annotations:
            cloud.google.com/service-account: "dns-service-account@dice-magic-test.iam.gserviceaccount.com"
        spec:
          containers:
          - image: gcr.io/dice-magic-test/letsencrypt-dev:latest
            name: letsencrypt