apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  tls:
    - hosts:
      - www.dev.dicemagic.io
      - api.dev.dicemagic.io
      secretName: letsencrypt-certs
  rules:
  - host: www.dev.dicemagic.io
    http:
      paths:
      - path: /
        backend:
          serviceName: www-service
          servicePort: 80
  - host: api.dev.dicemagic.io
    http:
      paths:
      - path: /
        backend:
          serviceName: dice-magic-app-service
          servicePort: 80