steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'pull-dice-server'
  args: ['pull', 'gcr.io/$PROJECT_ID/dice-server:latest']

- name: 'gcr.io/cloud-builders/go'
  args: ['get', '.']
  dir: 'app/dice-server'
  env: ['PROJECT_ROOT=app/dice-server']

- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  dir: 'app/dice-server'
  env: ['PROJECT_ROOT=app/dice-server']

- name: 'gcr.io/cloud-builders/go'
  args: ['test', '.']
  dir: 'app/dice-server'
  env: ['PROJECT_ROOT=app/dice-server']

- name: 'gcr.io/cloud-builders/docker'
  dir: 'app/dice-server'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/dice-server:latest',
            '-t', 'gcr.io/$PROJECT_ID/dice-server:$COMMIT_SHA',
            '--cache-from', 'gcr.io/$PROJECT_ID/dice-server:latest',
            '-f', 'slim.dockerfile',
            '.'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/k8s-dice-magic/dice-server:$COMMIT_SHA"]

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - dice-magic-app
  - dice-server=gcr.io/k8s-dice-magic/dice-server:$COMMIT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=dice-magic'

tags: ['$COMMIT_SHA']
images: 
- 'gcr.io/$PROJECT_ID/dice-server:latest'