apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt-job-first-run
  labels:
    app: letsencrypt
spec:
  template:
    metadata:
      name: letsencrypt
      annotations:
        cloud.google.com/service-account: "dns-service-account@dice-magic-test.iam.gserviceaccount.com"
      labels:
        app: letsencrypt
    spec:
      serviceAccountName: secret-manager
      containers:
      - image: gcr.io/dice-magic-test/letsencrypt-dev:latest
        name: letsencrypt
        imagePullPolicy: Always
        ports:
        - name: letsencrypt
          containerPort: 8080
        volumeMounts:
        - mountPath: /etc/certbot-dns
          name: certbot-dns
          readOnly: true
        envFrom:
        - configMapRef:
            name: certbot-config
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
      restartPolicy: Never
      volumes:
      - name: certbot-dns
        secret:
          defaultMode: 420
          secretName: certbot-dns 
  backoffLimit: 0