steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/letsencrypt:latest']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'letsencrypt'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/letsencrypt:latest',
            '-t', 'gcr.io/$PROJECT_ID/letsencrypt:$COMMIT_SHA',
            '--cache-from', 'gcr.io/$PROJECT_ID/letsencrypt:latest',
            '-f','dockerfile',
            '.'
        ]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/k8s-dice-magic/letsencrypt:$COMMIT_SHA"]

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - cronjob
  - letsencrypt-job
  - letsencrypt=gcr.io/k8s-dice-magic/letsencrypt:$COMMIT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=dice-magic'
tags: ['$COMMIT_SHA']
images:
- 'gcr.io/$PROJECT_ID/letsencrypt:latest'